# Generated by Django 5.1.5 on 2025-02-10 13:14

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("authen", "0002_gender_alter_customuser_avatar_and_more"),
        ("groups_custumer", "__first__"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SportCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=250, verbose_name="Спортивный разряд"
                    ),
                ),
            ],
            options={
                "verbose_name": "Спортивный разряд",
                "verbose_name_plural": "Спортивный разряд",
                "db_table": "sport_category",
            },
        ),
        migrations.CreateModel(
            name="TypeRepresentatives",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=250, verbose_name="Представители"
                    ),
                ),
            ],
            options={
                "verbose_name": "Тип родства",
                "verbose_name_plural": "Тип родства",
                "db_table": "type_representatives",
            },
        ),
        migrations.CreateModel(
            name="Cashier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=250, verbose_name="Касса"),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, null=True, verbose_name="Комментарий"
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Владелец",
                    ),
                ),
            ],
            options={
                "verbose_name": "Касса",
                "verbose_name_plural": "Касса",
                "db_table": "cashier",
            },
        ),
        migrations.CreateModel(
            name="Custumer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "full_name",
                    models.CharField(max_length=250, verbose_name="Ф.И.О"),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True,
                        max_length=250,
                        null=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Phone number must be entered in the format: '+9989999999'. Up to 15 digits allowed.",
                                regex="^\\+?1?\\d{9,15}$",
                            )
                        ],
                        verbose_name="Телефон",
                    ),
                ),
                (
                    "birth_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="День рождения"
                    ),
                ),
                (
                    "address",
                    models.CharField(
                        blank=True,
                        max_length=250,
                        null=True,
                        verbose_name="Адрес",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        max_length=254,
                        null=True,
                        verbose_name="E-mail",
                    ),
                ),
                (
                    "contract_number",
                    models.CharField(
                        blank=True,
                        max_length=250,
                        null=True,
                        verbose_name="Номер договора",
                    ),
                ),
                (
                    "contract_type",
                    models.CharField(
                        blank=True,
                        max_length=250,
                        null=True,
                        verbose_name="Тип договора",
                    ),
                ),
                (
                    "strat_date",
                    models.DateField(
                        blank=True,
                        null=True,
                        verbose_name="Дата начала обучения",
                    ),
                ),
                (
                    "photo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="custumer/",
                        verbose_name="Фото",
                    ),
                ),
                (
                    "gender",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="authen.gender",
                        verbose_name="Пол",
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        to="groups_custumer.groupsclass",
                        verbose_name="Группы",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Владелец",
                    ),
                ),
                (
                    "sport_category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="custumer.sportcategory",
                        verbose_name="Спортивный разряд",
                    ),
                ),
            ],
            options={
                "verbose_name": "Клиент",
                "verbose_name_plural": "Клиент",
                "db_table": "custumer",
            },
        ),
        migrations.CreateModel(
            name="CustumerDocs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        max_length=250,
                        null=True,
                        verbose_name="Название",
                    ),
                ),
                (
                    "files",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="custumer_files/",
                        verbose_name="Файл",
                    ),
                ),
                (
                    "custumer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="custumer.custumer",
                        verbose_name="Клиент",
                    ),
                ),
            ],
            options={
                "verbose_name": "Документы",
                "verbose_name_plural": "Документы",
                "db_table": "custumer_docs",
            },
        ),
        migrations.CreateModel(
            name="CustumerSubscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "number_classes",
                    models.BigIntegerField(
                        blank=True,
                        null=True,
                        verbose_name="Количество занятий",
                    ),
                ),
                (
                    "remained",
                    models.BigIntegerField(
                        blank=True, null=True, verbose_name="Остался"
                    ),
                ),
                (
                    "start_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Дата начала"
                    ),
                ),
                (
                    "end_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Дата окончания"
                    ),
                ),
                (
                    "unlimited",
                    models.BooleanField(
                        default=False, verbose_name="Безлимитный"
                    ),
                ),
                (
                    "total_cost",
                    models.BigIntegerField(
                        blank=True,
                        null=True,
                        verbose_name="Итоговая стоимость",
                    ),
                ),
                (
                    "is_free",
                    models.BooleanField(
                        default=False, verbose_name="Бесплатно"
                    ),
                ),
                (
                    "is_blok",
                    models.BooleanField(
                        default=False, verbose_name="Закрывать"
                    ),
                ),
                ("closing_date", models.DateField(blank=True, null=True)),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Время создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateField(
                        auto_now=True, verbose_name="Время обновления"
                    ),
                ),
                (
                    "custumer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="custumer.custumer",
                        verbose_name="Клиент",
                    ),
                ),
                (
                    "groups",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="groups_custumer.groupsclass",
                        verbose_name="Группы",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Владелец",
                    ),
                ),
            ],
            options={
                "verbose_name": "Абонемент",
                "verbose_name_plural": "Абонемент",
                "db_table": "custumer_subscription",
            },
        ),
        migrations.CreateModel(
            name="CustumerSubscriptonPayment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "summ",
                    models.BigIntegerField(
                        blank=True, null=True, verbose_name="Сумма платежа"
                    ),
                ),
                (
                    "summ_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Дата платежа"
                    ),
                ),
                (
                    "count",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Не оплачено"
                    ),
                ),
                (
                    "is_blok",
                    models.BooleanField(
                        default=False, verbose_name="Закрывать"
                    ),
                ),
                (
                    "cashier",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="custumer.cashier",
                        verbose_name="Касса",
                    ),
                ),
                (
                    "custumer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="custumer.custumer",
                        verbose_name="Клиент",
                    ),
                ),
                (
                    "groups",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="groups_custumer.groupsclass",
                        verbose_name="Группы",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Владелец",
                    ),
                ),
                (
                    "subscription",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="custumer.custumersubscription",
                        verbose_name="Абонемент",
                    ),
                ),
            ],
            options={
                "verbose_name": "Платежа",
                "verbose_name_plural": "Платежа",
                "db_table": "custumer_payment",
            },
        ),
        migrations.CreateModel(
            name="CustumerRepresentatives",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "full_name",
                    models.CharField(
                        blank=True,
                        max_length=250,
                        null=True,
                        verbose_name="Ф.И.О",
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True,
                        max_length=250,
                        null=True,
                        verbose_name="Телефон",
                    ),
                ),
                (
                    "work",
                    models.CharField(
                        blank=True,
                        max_length=250,
                        null=True,
                        verbose_name="Место работы",
                    ),
                ),
                (
                    "custumer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="custumer.custumer",
                        verbose_name="Клиент",
                    ),
                ),
                (
                    "type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="custumer.typerepresentatives",
                        verbose_name="Тип родства",
                    ),
                ),
            ],
            options={
                "verbose_name": "Представители",
                "verbose_name_plural": "Представители",
                "db_table": "custumer_representatives",
            },
        ),
    ]
