# Generated by Django 5.1.5 on 2025-02-10 17:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("custumer", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="custumersubscriptonpayment",
            name="sub_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
