# Generated by Django 5.1.5 on 2025-02-10 17:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("custumer", "0002_custumersubscriptonpayment_sub_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="custumersubscriptonpayment",
            name="is_pay",
            field=models.BooleanField(default=False),
        ),
    ]
