# Generated by Django 5.1.5 on 2025-02-10 20:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("custumer", "0004_alter_custumersubscriptonpayment_subscription"),
    ]

    operations = [
        migrations.AddField(
            model_name="custumersubscriptonpayment",
            name="create_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
