# Generated by Django 5.1.5 on 2025-02-10 21:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("custumer", "0005_custumersubscriptonpayment_create_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="custumersubscriptonpayment",
            name="update_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
