# Generated by Django 5.1.5 on 2025-02-12 16:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("custumer", "0006_custumersubscriptonpayment_update_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="custumer",
            name="is_none",
            field=models.BooleanField(default=False),
        ),
    ]
