# Generated by Django 5.1.5 on 2025-02-12 20:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("custumer", "0007_custumer_is_none"),
    ]

    operations = [
        migrations.AddField(
            model_name="custumersubscription",
            name="attendance_status",
            field=models.CharField(
                choices=[
                    ("paid", "Оплачено"),
                    ("unpaid", "Не оплачено"),
                    ("none", "Бесплатно"),
                ],
                default="none",
                max_length=50,
                verbose_name="Статус посещения",
            ),
        ),
    ]
