# Generated by Django 5.1.5 on 2025-02-13 09:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authen", "0003_company_customuser_company"),
        ("custumer", "0008_custumersubscription_attendance_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="cashier",
            name="company",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="authen.company",
                verbose_name="Компания",
            ),
        ),
        migrations.AddField(
            model_name="custumer",
            name="company",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="authen.company",
                verbose_name="Компания",
            ),
        ),
        migrations.AddField(
            model_name="custumersubscription",
            name="company",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="authen.company",
                verbose_name="Компания",
            ),
        ),
        migrations.AddField(
            model_name="custumersubscriptonpayment",
            name="company",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="authen.company",
                verbose_name="Компания",
            ),
        ),
    ]
