# Generated by Django 5.1.5 on 2025-02-16 10:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("custumer", "0009_cashier_company_custumer_company_and_more"),
        ("groups_custumer", "0011_alter_groupsclass_type_sport"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="custumersubscription",
            name="groups",
        ),
        migrations.AddField(
            model_name="custumersubscription",
            name="groups",
            field=models.ManyToManyField(
                blank=True,
                to="groups_custumer.groupsclass",
                verbose_name="Группы",
            ),
        ),
    ]
