# Generated by Django 5.1.5 on 2025-02-16 18:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authen", "0004_alter_company_name_typesportscompany"),
        ("custumer", "0010_remove_custumersubscription_groups_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SubscriptionTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=250, verbose_name="Название"),
                ),
                ("price", models.IntegerField(verbose_name="Стоимость")),
                ("expired", models.IntegerField(verbose_name="Срок действия")),
                (
                    "number_classes",
                    models.IntegerField(verbose_name="Количество занятий"),
                ),
                (
                    "is_free",
                    models.BooleanField(
                        default=False, verbose_name="Безлимитный"
                    ),
                ),
                (
                    "is_day",
                    models.BooleanField(default=False, verbose_name="Дни"),
                ),
                (
                    "is_week",
                    models.BooleanField(default=False, verbose_name="Недели"),
                ),
                (
                    "is_month",
                    models.BooleanField(default=False, verbose_name="Месяцы"),
                ),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="authen.company",
                        verbose_name="Компания",
                    ),
                ),
            ],
            options={
                "verbose_name": "Шаблоны абонементов",
                "verbose_name_plural": "Шаблоны абонементов",
                "db_table": "subscription_template",
            },
        ),
    ]
