# Generated by Django 5.1.5 on 2025-02-17 09:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("custumer", "0011_subscriptiontemplate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscriptiontemplate",
            name="number_classes",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Количество занятий"
            ),
        ),
    ]
