# Generated by Django 5.1.5 on 2025-02-17 10:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("custumer", "0012_alter_subscriptiontemplate_number_classes"),
    ]

    operations = [
        migrations.RenameField(
            model_name="subscriptiontemplate",
            old_name="is_free",
            new_name="unlimited",
        ),
    ]
