# Generated by Django 5.1.5 on 2025-07-30 13:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("achievements", "0001_initial"),
        ("custumer", "0013_rename_is_free_subscriptiontemplate_unlimited"),
    ]

    operations = [
        migrations.AddField(
            model_name="custumer",
            name="achievements",
            field=models.ManyToManyField(
                blank=True,
                related_name="customers",
                to="achievements.achievement",
                verbose_name="Достижения",
            ),
        ),
    ]
