# Generated by Django 5.1.5 on 2025-08-01 09:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("competitions", "0001_initial"),
        ("custumer", "0014_custumer_achievements"),
    ]

    operations = [
        migrations.AddField(
            model_name="custumer",
            name="competitions",
            field=models.ManyToManyField(
                blank=True,
                related_name="customers",
                to="competitions.competitions",
                verbose_name="Соревнования",
            ),
        ),
    ]
