# Generated by Django 5.1.5 on 2025-08-06 13:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("custumer", "0015_custumer_competitions"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="custumer",
            options={
                "verbose_name": "Клиент",
                "verbose_name_plural": "Клиенты",
            },
        ),
        migrations.AlterModelOptions(
            name="custumerdocs",
            options={
                "verbose_name": "Документ",
                "verbose_name_plural": "Документы",
            },
        ),
        migrations.AlterModelOptions(
            name="custumersubscription",
            options={
                "verbose_name": "Абонемент",
                "verbose_name_plural": "Абонементы",
            },
        ),
        migrations.AlterModelOptions(
            name="custumersubscriptonpayment",
            options={
                "verbose_name": "Платеж",
                "verbose_name_plural": "Платежи",
            },
        ),
        migrations.AlterModelOptions(
            name="sportcategory",
            options={
                "verbose_name": "Спортивный разряд",
                "verbose_name_plural": "Спортивные разряды",
            },
        ),
        migrations.AddField(
            model_name="custumer",
            name="user",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="client_profile",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Пользователь клиента (личный кабинет)",
            ),
        ),
    ]
