# Generated by Django 5.1.5 on 2025-08-06 14:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "custumer",
            "0016_alter_custumer_options_alter_custumerdocs_options_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="custumer",
            name="is_send",
            field=models.BooleanField(
                default=False, verbose_name="Приглашение отправлено"
            ),
        ),
    ]
