# Generated by Django 5.1.5 on 2025-08-11 14:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("custumer", "0017_custumer_is_send"),
    ]

    operations = [
        migrations.AlterField(
            model_name="custumersubscription",
            name="remained",
            field=models.BigIntegerField(
                blank=True, null=True, verbose_name="Колличество посещений"
            ),
        ),
    ]
