# Generated by Django 5.1.5 on 2025-08-12 09:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("custumer", "0018_alter_custumersubscription_remained"),
    ]

    operations = [
        migrations.AddField(
            model_name="custumer",
            name="balance",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Баланс (баллы)"
            ),
        ),
    ]
