# Generated by Django 5.1.5 on 2025-08-21 15:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("custumer", "0019_custumer_balance"),
    ]

    operations = [
        migrations.AlterField(
            model_name="custumersubscriptonpayment",
            name="subscription",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payments",
                to="custumer.custumersubscription",
                verbose_name="Абонемент",
            ),
        ),
    ]
