# Generated by Django 5.1.5 on 2025-08-28 13:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("achievements", "0003_achievement_points"),
        ("competitions", "0007_custumercompetitionresult_discipline"),
        ("custumer", "0020_alter_custumersubscriptonpayment_subscription"),
        ("groups_custumer", "0022_groupclasses_is_manual"),
        ("market", "0002_product_description"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PointsHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("points", models.IntegerField(verbose_name="Баллы")),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("attendance", "Посещение занятия"),
                            ("achievement", "Достижение"),
                            ("competition", "Соревнование"),
                            ("manual", "Ручное начисление"),
                            ("purchase", "Покупка товара"),
                        ],
                        verbose_name="Причина",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, null=True, verbose_name="Описание"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Время создания"
                    ),
                ),
                (
                    "achievement",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="achievements.achievement",
                        verbose_name="Достижение",
                    ),
                ),
                (
                    "attendance_record",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="groups_custumer.groupclassesscustumer",
                        verbose_name="Запись посещения",
                    ),
                ),
                (
                    "awarded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Начислил",
                    ),
                ),
                (
                    "competition_result",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="competitions.custumercompetitionresult",
                        verbose_name="Результат соревнования",
                    ),
                ),
                (
                    "custumer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="custumer.custumer",
                        verbose_name="Клиент",
                    ),
                ),
                (
                    "purchase",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="market.purchase",
                        verbose_name="Покупка",
                    ),
                ),
            ],
            options={
                "verbose_name": "История начисления баллов",
                "verbose_name_plural": "История начисления баллов",
                "db_table": "points_history",
                "ordering": ["-created_at"],
            },
        ),
    ]
