# Generated by Django 5.1.5 on 2025-09-01 14:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("custumer", "0021_pointshistory"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="sportcategory",
            options={
                "ordering": ["level"],
                "verbose_name": "Спортивный разряд",
                "verbose_name_plural": "Спортивные разряды",
            },
        ),
        migrations.AddField(
            model_name="sportcategory",
            name="description",
            field=models.TextField(
                blank=True, null=True, verbose_name="Описание разряда"
            ),
        ),
        migrations.AddField(
            model_name="sportcategory",
            name="level",
            field=models.PositiveIntegerField(
                default=1,
                help_text="Чем выше число, тем выше разряд (например: 1-новичок, 10-мастер спорта)",
                verbose_name="Уровень разряда",
            ),
        ),
    ]
