# Generated by Django 5.1.5 on 2025-09-05 14:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("custumer", "0022_alter_sportcategory_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="custumersubscription",
            name="is_blok",
            field=models.BooleanField(default=False, verbose_name="Закрыть"),
        ),
        migrations.AlterField(
            model_name="custumersubscription",
            name="remained",
            field=models.BigIntegerField(
                blank=True, null=True, verbose_name="Количество посещений"
            ),
        ),
    ]
