# Generated by Django 5.1.5 on 2025-09-24 15:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("custumer", "0023_alter_custumersubscription_is_blok_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscriptiontemplate",
            name="is_free",
            field=models.BooleanField(default=False, verbose_name="Бесплатно"),
        ),
    ]
