# Generated by Django 5.1.5 on 2025-11-14 14:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("custumer", "0024_subscriptiontemplate_is_free"),
    ]

    operations = [
        migrations.AlterField(
            model_name="custumersubscriptonpayment",
            name="is_blok",
            field=models.BooleanField(default=False, verbose_name="Закрыто"),
        ),
        migrations.AlterField(
            model_name="custumersubscriptonpayment",
            name="is_pay",
            field=models.BooleanField(default=False, verbose_name="Оплачено"),
        ),
    ]
