# Generated by Django 5.1.5 on 2025-11-26 19:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authen", "0005_userprofile"),
        ("custumer", "0025_alter_custumersubscriptonpayment_is_blok_and_more"),
        ("groups_custumer", "0024_groupsclass_end_training"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="custumersubscription",
            index=models.Index(
                fields=["custumer", "start_date", "end_date"],
                name="idx_sub_cust_dates",
            ),
        ),
        migrations.AddIndex(
            model_name="custumersubscription",
            index=models.Index(
                fields=["attendance_status", "is_blok"], name="idx_sub_status"
            ),
        ),
        migrations.AddIndex(
            model_name="custumersubscription",
            index=models.Index(fields=["end_date"], name="idx_sub_end_date"),
        ),
        migrations.AddIndex(
            model_name="custumersubscription",
            index=models.Index(
                fields=["unlimited", "number_classes", "remained"],
                name="idx_sub_classes",
            ),
        ),
        migrations.AddIndex(
            model_name="custumersubscription",
            index=models.Index(fields=["company"], name="idx_sub_company"),
        ),
    ]
