# Generated by Django 5.1.5 on 2025-11-26 20:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("custumer", "0026_custumersubscription_idx_sub_cust_dates_and_more"),
        ("groups_custumer", "0024_groupsclass_end_training"),
    ]

    operations = [
        migrations.AddField(
            model_name="custumersubscriptonpayment",
            name="attendance_record",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payment_record",
                to="groups_custumer.groupclassesscustumer",
                verbose_name="Запись посещения",
            ),
        ),
        migrations.AlterField(
            model_name="custumersubscriptonpayment",
            name="sub_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Дата посещения"
            ),
        ),
    ]
