# Generated by Django 5.1.5 on 2025-11-26 20:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authen", "0005_userprofile"),
        (
            "custumer",
            "0027_custumersubscriptonpayment_attendance_record_and_more",
        ),
        ("groups_custumer", "0024_groupsclass_end_training"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="custumersubscriptonpayment",
            index=models.Index(
                fields=["attendance_record"], name="idx_payment_attendance"
            ),
        ),
        migrations.AddIndex(
            model_name="custumersubscriptonpayment",
            index=models.Index(
                fields=["custumer", "sub_date"], name="idx_payment_cust_date"
            ),
        ),
        migrations.AddIndex(
            model_name="custumersubscriptonpayment",
            index=models.Index(
                fields=["subscription"], name="idx_payment_sub"
            ),
        ),
    ]
