# Generated by Django 5.1.5 on 2025-08-18 13:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("news", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="news",
            name="status",
            field=models.CharField(
                choices=[("Черновик", "Draft"), ("Опубликовано", "Published")],
                default="Черновик",
                max_length=50,
                verbose_name="Статус",
            ),
        ),
    ]
