# Generated by Django 5.1.5 on 2025-08-20 12:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("achievements", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="achievement",
            name="tag",
            field=models.CharField(
                choices=[
                    ("basic", "Базовый"),
                    ("advanced", "Продвинутый"),
                    ("pro", "Профи"),
                ],
                default="basic",
                help_text="Выберите теги для достижения",
                max_length=255,
                verbose_name="Тэг",
            ),
        ),
    ]
