# Generated by Django 5.1.5 on 2025-08-28 13:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("achievements", "0002_achievement_tag"),
    ]

    operations = [
        migrations.AddField(
            model_name="achievement",
            name="points",
            field=models.IntegerField(
                default=0,
                help_text="Баллы за достижение",
                verbose_name="Баллы",
            ),
        ),
    ]
