# Generated by Django 5.1.5 on 2025-09-08 16:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("achievements", "0003_achievement_points"),
    ]

    operations = [
        migrations.AlterField(
            model_name="achievement",
            name="tag",
            field=models.CharField(
                choices=[
                    ("basic", "Базовый"),
                    ("advanced", "Продвинутый"),
                    ("pro", "Профи"),
                    ("water_element", "Водная стихия (базовый уровень)"),
                    (
                        "swimming_skills",
                        "Умею плавать (технический, средний уровень)",
                    ),
                    (
                        "champion_path",
                        "Чемпионский путь (соревнования, личные достижения)",
                    ),
                    ("team_captain", "Капитан команды (лидерские навыки)"),
                    (
                        "land_champion",
                        "Сухопутный чемпион (достижения на суше)",
                    ),
                    (
                        "media_champion",
                        "Медиа-чемпион (социальные достижения)",
                    ),
                    (
                        "challenge_master",
                        "Челлендж-мастер (командные испытания)",
                    ),
                ],
                default="basic",
                help_text="Выберите теги для достижения",
                max_length=255,
                verbose_name="Тэг",
            ),
        ),
    ]
