# Generated by Django 5.1.5 on 2025-02-10 13:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("employe", "__first__"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TypeSports",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=250, verbose_name="Вид спорта"
                    ),
                ),
            ],
            options={
                "verbose_name": "Вид спорта",
                "verbose_name_plural": "Вид спорта",
                "db_table": "type_sport",
            },
        ),
        migrations.CreateModel(
            name="Week",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=250, verbose_name="Неделя"),
                ),
            ],
            options={
                "verbose_name": "Неделя",
                "verbose_name_plural": "Неделя",
                "db_table": "week",
            },
        ),
        migrations.CreateModel(
            name="GroupClasses",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="Дата")),
                ("strat", models.TimeField(verbose_name="Начало")),
                ("end", models.TimeField(verbose_name="Конец")),
                (
                    "comment",
                    models.TextField(
                        blank=True, null=True, verbose_name="Комментарий"
                    ),
                ),
                (
                    "attendance_status",
                    models.CharField(
                        choices=[
                            ("attended", "Был"),
                            ("not_attended", "Не Был"),
                            ("none", "None"),
                        ],
                        default="none",
                        max_length=50,
                        verbose_name="Статус посещения",
                    ),
                ),
                (
                    "employe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="employe.employe",
                        verbose_name="Тренеры",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Занятие",
                "verbose_name_plural": "Занятие",
                "db_table": "group_classes",
            },
        ),
        migrations.CreateModel(
            name="GroupClassessCustumer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Дата"
                    ),
                ),
                ("class_time", models.TimeField(blank=True, null=True)),
                (
                    "attendance_status",
                    models.CharField(
                        choices=[
                            ("attended", "Был"),
                            ("not_attended", "Не Был"),
                            ("none", "None"),
                        ],
                        default="none",
                        max_length=50,
                        verbose_name="Статус посещения",
                    ),
                ),
                (
                    "gr_class",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="groups_custumer.groupclasses",
                        verbose_name="Занятие",
                    ),
                ),
            ],
            options={
                "verbose_name": "Посещаемость",
                "verbose_name_plural": "Посещаемость",
                "db_table": "group_classes_custumer",
            },
        ),
        migrations.CreateModel(
            name="GroupsClass",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=250, verbose_name="Название"),
                ),
                (
                    "strat_training",
                    models.DateField(
                        blank=True, null=True, verbose_name="Начало обучения"
                    ),
                ),
                (
                    "position",
                    models.BigIntegerField(
                        blank=True, null=True, verbose_name="Позиция"
                    ),
                ),
                (
                    "employe_id",
                    models.ManyToManyField(
                        blank=True,
                        to="employe.employe",
                        verbose_name="Тренеры",
                    ),
                ),
                (
                    "owner_id",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="owner",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Владелец",
                    ),
                ),
                (
                    "type_sport",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="groups_custumer.typesports",
                        verbose_name="Вид спорта",
                    ),
                ),
            ],
            options={
                "verbose_name": "Группа класса",
                "verbose_name_plural": "Группа класса",
                "db_table": "groups_class",
            },
        ),
        migrations.AddField(
            model_name="groupclasses",
            name="groups_id",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="group_class",
                to="groups_custumer.groupsclass",
                verbose_name="Группа класса",
            ),
        ),
        migrations.CreateModel(
            name="Schedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "strat_time",
                    models.TimeField(
                        blank=True, null=True, verbose_name="Время начала"
                    ),
                ),
                (
                    "end_time",
                    models.TimeField(
                        blank=True, null=True, verbose_name="Время окончания"
                    ),
                ),
                (
                    "groups_id",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="groups",
                        to="groups_custumer.groupsclass",
                        verbose_name="Группа класса",
                    ),
                ),
                (
                    "week",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="groups_custumer.week",
                        verbose_name="День недели",
                    ),
                ),
            ],
            options={
                "verbose_name": "Расписание",
                "verbose_name_plural": "Расписание",
                "db_table": "schedule",
            },
        ),
    ]
