# Generated by Django 5.1.5 on 2025-02-10 13:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("custumer", "0001_initial"),
        ("groups_custumer", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="groupclassesscustumer",
            name="custumer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="custumer_id",
                to="custumer.custumer",
                verbose_name="Клиенты",
            ),
        ),
        migrations.AddField(
            model_name="groupclassesscustumer",
            name="used_subscription",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="used_attendances",
                to="custumer.custumersubscription",
                verbose_name="Использованная подписка",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="groupclassesscustumer",
            unique_together={("custumer", "gr_class", "date")},
        ),
    ]
