# Generated by Django 5.1.5 on 2025-02-10 21:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("groups_custumer", "0003_groupclassesscustumer_create_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="groupclassesscustumer",
            name="update_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
