# Generated by Django 5.1.5 on 2025-02-11 13:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("groups_custumer", "0004_groupclassesscustumer_update_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="groupclassesscustumer",
            name="is_block",
            field=models.BooleanField(default=False),
        ),
    ]
