# Generated by Django 5.1.5 on 2025-02-12 16:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("groups_custumer", "0005_groupclassesscustumer_is_block"),
    ]

    operations = [
        migrations.AddField(
            model_name="groupclassesscustumer",
            name="is_none",
            field=models.BooleanField(default=False),
        ),
    ]
