# Generated by Django 5.1.5 on 2025-02-13 09:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authen", "0003_company_customuser_company"),
        ("groups_custumer", "0006_groupclassesscustumer_is_none"),
    ]

    operations = [
        migrations.AddField(
            model_name="groupclasses",
            name="company",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="authen.company",
                verbose_name="Компания",
            ),
        ),
        migrations.AddField(
            model_name="groupclassesscustumer",
            name="company",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="authen.company",
                verbose_name="Компания",
            ),
        ),
        migrations.AddField(
            model_name="groupsclass",
            name="company",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="authen.company",
                verbose_name="Компания",
            ),
        ),
    ]
