# Generated by Django 5.1.5 on 2025-02-14 11:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("groups_custumer", "0009_alter_groupsclass_type_sport"),
    ]

    operations = [
        migrations.AlterField(
            model_name="groupsclass",
            name="type_sport",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="groups_custumer.typesports",
                verbose_name="Вид спорта",
            ),
        ),
    ]
