# Generated by Django 5.1.5 on 2025-02-14 11:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authen", "0004_alter_company_name_typesportscompany"),
        ("groups_custumer", "0010_alter_groupsclass_type_sport"),
    ]

    operations = [
        migrations.AlterField(
            model_name="groupsclass",
            name="type_sport",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="authen.typesportscompany",
                verbose_name="Вид спорта",
            ),
        ),
    ]
