# Generated by Django 5.1.5 on 2025-02-28 21:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("groups_custumer", "0011_alter_groupsclass_type_sport"),
    ]

    operations = [
        migrations.AddField(
            model_name="schedule",
            name="name",
            field=models.CharField(
                blank=True,
                max_length=250,
                null=True,
                verbose_name="Имя занятиям",
            ),
        ),
    ]
