# Generated by Django 5.1.5 on 2025-02-28 22:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("groups_custumer", "0012_schedule_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="week",
            name="short_name",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
