# Generated by Django 5.1.5 on 2025-03-02 17:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("groups_custumer", "0013_week_short_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="ClasessProgramm",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "stages",
                    models.CharField(max_length=250, verbose_name="Этапы"),
                ),
                (
                    "distance",
                    models.CharField(max_length=250, verbose_name="Дистанция"),
                ),
                (
                    "style",
                    models.CharField(max_length=250, verbose_name="Стиль"),
                ),
                (
                    "comments",
                    models.TextField(
                        blank=True, null=True, verbose_name="Комментарии"
                    ),
                ),
                (
                    "rest",
                    models.CharField(max_length=250, verbose_name="Отдых"),
                ),
                (
                    "classes",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="groups_custumer.groupclasses",
                    ),
                ),
            ],
            options={
                "verbose_name": "Занятие программа ",
                "verbose_name_plural": "Занятие программа",
                "db_table": "classes_programm",
            },
        ),
    ]
