# Generated by Django 5.1.5 on 2025-03-02 18:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("groups_custumer", "0014_clasessprogramm"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clasessprogramm",
            name="classes",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="classes",
                to="groups_custumer.groupclasses",
            ),
        ),
    ]
