# Generated by Django 5.1.5 on 2025-03-02 19:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("groups_custumer", "0015_alter_clasessprogramm_classes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="groupclassesscustumer",
            name="attendance_status",
            field=models.CharField(
                choices=[
                    ("not_attended", "Не Был"),
                    ("attended_2", "Был (2)"),
                    ("attended_3", "Был (3)"),
                    ("attended_4", "Был (4)"),
                    ("attended_5", "Был (5)"),
                    ("attended_10", "Был (10)"),
                ],
                default="not_attended",
                max_length=20,
                verbose_name="Статус посещения",
            ),
        ),
    ]
