# Generated by Django 5.1.5 on 2025-03-02 20:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "groups_custumer",
            "0016_alter_groupclassesscustumer_attendance_status",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="groupclassesscustumer",
            name="attendance_status",
            field=models.CharField(
                choices=[
                    ("not_attended", "Не Был"),
                    ("attended_2", "Был (2)"),
                    ("attended_3", "Был (3)"),
                    ("attended_4", "Был (4)"),
                    ("attended_5", "Был (5)"),
                    ("attended_10", "Был (10)"),
                    ("none", "None"),
                ],
                default="none",
                max_length=20,
                verbose_name="Статус посещения",
            ),
        ),
    ]
