# Generated by Django 5.1.5 on 2025-03-02 22:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "groups_custumer",
            "0017_alter_groupclassesscustumer_attendance_status",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="groupclasses",
            name="name",
            field=models.CharField(
                blank=True,
                max_length=250,
                null=True,
                verbose_name="Имя занятиям",
            ),
        ),
    ]
