# Generated by Django 5.1.5 on 2025-07-30 13:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("groups_custumer", "0018_groupclasses_name"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="week",
            options={
                "verbose_name": "День недели",
                "verbose_name_plural": "Дени недели",
            },
        ),
    ]
