# Generated by Django 5.1.5 on 2025-08-06 13:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("groups_custumer", "0019_alter_week_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="week",
            options={
                "verbose_name": "День недели",
                "verbose_name_plural": "Дни недели",
            },
        ),
    ]
