# Generated by Django 5.1.5 on 2025-08-21 11:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("groups_custumer", "0020_alter_week_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="groupclassesscustumer",
            name="comment",
            field=models.TextField(
                blank=True, null=True, verbose_name="Комментарий"
            ),
        ),
    ]
