# Generated by Django 5.1.5 on 2025-08-26 09:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("groups_custumer", "0021_groupclassesscustumer_comment"),
    ]

    operations = [
        migrations.AddField(
            model_name="groupclasses",
            name="is_manual",
            field=models.BooleanField(
                default=False, verbose_name="Ручное добавление"
            ),
        ),
    ]
