# Generated by Django 5.1.5 on 2025-11-03 11:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authen", "0005_userprofile"),
        ("custumer", "0024_subscriptiontemplate_is_free"),
        ("employe", "0006_alter_employeroll_options_alter_employe_roll"),
        ("groups_custumer", "0022_groupclasses_is_manual"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="groupclasses",
            index=models.Index(
                fields=["groups_id", "date"], name="idx_gc_groups_date"
            ),
        ),
        migrations.AddIndex(
            model_name="groupclasses",
            index=models.Index(fields=["date"], name="idx_gc_date"),
        ),
        migrations.AddIndex(
            model_name="groupclassesscustumer",
            index=models.Index(
                fields=["gr_class", "date"], name="idx_gcc_class_date"
            ),
        ),
        migrations.AddIndex(
            model_name="groupclassesscustumer",
            index=models.Index(fields=["date"], name="idx_gcc_date"),
        ),
        migrations.AddIndex(
            model_name="groupclassesscustumer",
            index=models.Index(fields=["custumer"], name="idx_gcc_custumer"),
        ),
        migrations.AddIndex(
            model_name="groupclassesscustumer",
            index=models.Index(
                fields=["attendance_status"], name="idx_gcc_status"
            ),
        ),
        migrations.AddIndex(
            model_name="groupclassesscustumer",
            index=models.Index(fields=["is_block"], name="idx_gcc_is_block"),
        ),
    ]
