# Generated by Django 5.1.5 on 2025-11-04 13:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("groups_custumer", "0023_add_performance_indexes"),
    ]

    operations = [
        migrations.AddField(
            model_name="groupsclass",
            name="end_training",
            field=models.DateField(
                blank=True, null=True, verbose_name="Конец обучения"
            ),
        ),
    ]
