# Generated by Django 5.1.5 on 2025-02-13 09:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authen", "0003_company_customuser_company"),
        ("employe", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="employe",
            name="company",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="authen.company",
                verbose_name="Компания",
            ),
        ),
        migrations.AddField(
            model_name="employeroll",
            name="company",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="authen.company",
                verbose_name="Компания",
            ),
        ),
    ]
