# Generated by Django 5.1.5 on 2025-02-13 10:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("employe", "0002_employe_company_employeroll_company"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmployePermissions",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=250)),
            ],
        ),
        migrations.AddField(
            model_name="employeroll",
            name="perm",
            field=models.ManyToManyField(
                blank=True, to="employe.employepermissions"
            ),
        ),
    ]
