# Generated by Django 5.1.5 on 2025-02-14 11:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("employe", "0003_employepermissions_employeroll_perm"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmployePermissionsGroups",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=250, verbose_name="Название"),
                ),
            ],
            options={
                "verbose_name": "Доступные права Группы",
                "verbose_name_plural": "Доступные права Группы",
                "db_table": "employe_permissions_group",
            },
        ),
        migrations.AlterModelOptions(
            name="employepermissions",
            options={
                "verbose_name": "Доступные права",
                "verbose_name_plural": "Доступные права",
            },
        ),
        migrations.AlterField(
            model_name="employepermissions",
            name="name",
            field=models.CharField(max_length=250, verbose_name="Название"),
        ),
        migrations.AlterModelTable(
            name="employepermissions",
            table="employe_permissions",
        ),
        migrations.AddField(
            model_name="employepermissions",
            name="group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="employe.employepermissionsgroups",
                verbose_name="Группы",
            ),
        ),
    ]
