# Generated by Django 5.1.5 on 2025-02-14 12:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("employe", "0004_employepermissionsgroups_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employepermissions",
            name="group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="perm_group",
                to="employe.employepermissionsgroups",
                verbose_name="Группы",
            ),
        ),
    ]
