# Generated by Django 5.1.5 on 2025-08-06 13:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("employe", "0005_alter_employepermissions_group"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="employeroll",
            options={
                "verbose_name": "Роль сотрудника",
                "verbose_name_plural": "Роли сотрудников",
            },
        ),
        migrations.AlterField(
            model_name="employe",
            name="roll",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="employe.employeroll",
                verbose_name="Роль",
            ),
        ),
    ]
