# Generated by Django 5.1.5 on 2025-09-05 14:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("custumer", "0023_alter_custumersubscription_is_blok_and_more"),
        ("market", "0002_product_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="sport_category",
            field=models.ForeignKey(
                blank=True,
                help_text="Если указан разряд, товар могут купить только клиенты с этим разрядом или выше",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="custumer.sportcategory",
                verbose_name="Ограничение по разряду",
            ),
        ),
    ]
