# Generated by Django 5.1.5 on 2025-09-05 15:49

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "market",
            "0004_purchase_purchased_at_order_purchase_order_orderitem",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="purchase",
            unique_together={("product", "owner", "order")},
        ),
    ]
