# Generated by Django 5.1.5 on 2025-02-14 10:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authen", "0003_company_customuser_company"),
    ]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="name",
            field=models.CharField(max_length=250, verbose_name="Название"),
        ),
        migrations.CreateModel(
            name="TypeSportsCompany",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=250, verbose_name="Название"),
                ),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="authen.company",
                        verbose_name="Компания",
                    ),
                ),
            ],
            options={
                "verbose_name": "Тип Спорт Компания",
                "verbose_name_plural": "Тип Спорт Компания",
                "db_table": "type_sport_company",
            },
        ),
    ]
