###########################
# Общие настройки
###########################

# Прослушивать все интерфейсы, но для безопасности можно ограничить доступ на уровне firewall
bind 0.0.0.0

# Если к Redis нужен пароль – раскомментируйте и задайте пароль
# requirepass YOUR_SECURE_PASSWORD

# Работать в защищённом режиме
protected-mode no

# Порт, на котором запущен Redis
port 6379

# Логирование: вывод в стандартный вывод
loglevel notice
logfile ""

###########################
# Настройки персистентности
###########################

# Директория, куда будут сохраняться RDB и AOF файлы. Обязательно используйте volume
dir /data

# Снимки RDB – сохраняем базу при изменениях:
save 900 1
save 300 10
save 60 10000

# Включаем Append Only File для более надёжной записи изменений
appendonly yes
appendfilename "appendonly.aof"
appendfsync everysec

###########################
# Безопасность и управление памятью
###########################

# Если память исчерпана – отключаем запись (noeviction) или выбираем другую политику ("allkeys-lru", например)
maxmemory-policy noeviction

# По возможности, настройте системные параметры: обязательно включите overcommit_memory:
# В оперативной системе выполните: sysctl vm.overcommit_memory=1
