# Generated by Django 5.1.5 on 2025-08-01 09:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("competitions", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="competitions",
            unique_together={("name", "location", "date")},
        ),
    ]
