# Generated by Django 5.1.5 on 2025-08-11 15:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("competitions", "0002_alter_competitions_unique_together"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CustumerCompetitionResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "distance",
                    models.FloatField(
                        max_length=100, verbose_name="Дистанция"
                    ),
                ),
                (
                    "style",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Стиль",
                    ),
                ),
                (
                    "result_time",
                    models.TimeField(
                        max_length=50, verbose_name="Показанное время"
                    ),
                ),
                (
                    "place",
                    models.PositiveIntegerField(verbose_name="Занятое место"),
                ),
                (
                    "competition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="results",
                        to="competitions.competitions",
                        verbose_name="Соревнование",
                    ),
                ),
                (
                    "custumer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="results",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Клиент",
                    ),
                ),
            ],
            options={
                "verbose_name": "Результат соревнования",
                "verbose_name_plural": "Результаты соревнований",
                "unique_together": {
                    ("competition", "custumer", "distance", "style")
                },
            },
        ),
    ]
