# Generated by Django 5.1.5 on 2025-08-20 14:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("competitions", "0004_custumercompetitionresult_result_ms"),
    ]

    operations = [
        migrations.AlterField(
            model_name="competitions",
            name="status",
            field=models.CharField(
                choices=[("open", "Активно"), ("closed", "Завершено")],
                default="open",
                max_length=50,
                verbose_name="Статус",
            ),
        ),
    ]
