# Generated by Django 5.1.5 on 2025-08-22 15:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("competitions", "0005_alter_competitions_status"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="custumercompetitionresult",
            unique_together=set(),
        ),
    ]
