# Generated by Django 5.1.5 on 2025-08-22 15:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "competitions",
            "0006_alter_custumercompetitionresult_unique_together",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="custumercompetitionresult",
            name="discipline",
            field=models.CharField(
                blank=True,
                help_text="Название дисциплины (например: 'Плавание 50м вольный стиль')",
                max_length=255,
                null=True,
                verbose_name="Дисциплина",
            ),
        ),
    ]
