# Generated by Django 5.1.5 on 2025-08-31 10:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("competitions", "0007_custumercompetitionresult_discipline"),
        ("custumer", "0021_pointshistory"),
    ]

    operations = [
        migrations.AddField(
            model_name="custumercompetitionresult",
            name="sport_category",
            field=models.ForeignKey(
                blank=True,
                help_text="Разряд, полученный на этом соревновании",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="custumer.sportcategory",
                verbose_name="Полученный разряд",
            ),
        ),
    ]
