# Generated by Django 5.1.5 on 2025-09-06 10:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("competitions", "0008_custumercompetitionresult_sport_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="custumercompetitionresult",
            name="disqualification_comment",
            field=models.TextField(
                blank=True,
                help_text="Укажите причину дисквалификации",
                max_length=500,
                null=True,
                verbose_name="Причина дисквалификации",
            ),
        ),
        migrations.AddField(
            model_name="custumercompetitionresult",
            name="is_disqualified",
            field=models.BooleanField(
                default=False,
                help_text="Отметить, если участник дисквалифицирован",
                verbose_name="Дисквалифицирован",
            ),
        ),
        migrations.AlterField(
            model_name="custumercompetitionresult",
            name="place",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Не заполняется при дисквалификации",
                null=True,
                verbose_name="Занятое место",
            ),
        ),
        migrations.AlterField(
            model_name="custumercompetitionresult",
            name="result_ms",
            field=models.PositiveIntegerField(
                blank=True,
                default=0,
                help_text="Не заполняется при дисквалификации",
                null=True,
                verbose_name="Показанное время в мс",
            ),
        ),
        migrations.AlterField(
            model_name="custumercompetitionresult",
            name="result_time",
            field=models.TimeField(
                blank=True,
                help_text="Не заполняется при дисквалификации",
                max_length=50,
                null=True,
                verbose_name="Показанное время",
            ),
        ),
    ]
