# Generated by Django 5.1.5 on 2025-09-29 19:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "competitions",
            "0009_custumercompetitionresult_disqualification_comment_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="custumercompetitionresult",
            name="discipline",
            field=models.CharField(
                blank=True,
                help_text="Название дисциплины (например: 'Плавание вольный стиль')",
                max_length=255,
                null=True,
                verbose_name="Дисциплина",
            ),
        ),
        migrations.AlterField(
            model_name="custumercompetitionresult",
            name="style",
            field=models.CharField(
                blank=True,
                choices=[
                    ("25m", "25 метров"),
                    ("50m", "50 метров"),
                    ("open_water", "Открытая вода"),
                ],
                max_length=100,
                null=True,
                verbose_name="Стиль",
            ),
        ),
    ]
