# Generated by Django 5.1.5 on 2025-11-14 14:01

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "competitions",
            "0012_alter_custumercompetitionresult_result_time_ms",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="custumercompetitionresult",
            unique_together={
                (
                    "competition",
                    "custumer",
                    "distance",
                    "style",
                    "discipline",
                    "result_time_ms",
                )
            },
        ),
    ]
