# Generated by Django 5.1.5 on 2025-11-14 16:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "competitions",
            "0013_alter_custumercompetitionresult_unique_together",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="custumercompetitionresult",
            name="customer_id",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="ID клиента"
            ),
        ),
        migrations.AlterField(
            model_name="custumercompetitionresult",
            name="custumer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="results",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Клиент",
            ),
        ),
    ]
