# Generated by Django 5.1.5 on 2025-11-14 16:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("competitions", "0015_fill_customer_id_to_field"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="custumercompetitionresult",
            unique_together={
                (
                    "competition",
                    "customer_id",
                    "distance",
                    "style",
                    "discipline",
                    "result_time_ms",
                )
            },
        ),
        migrations.RemoveField(
            model_name="custumercompetitionresult",
            name="custumer",
        ),
    ]
