# Generated by Django 5.1.5 on 2025-11-14 16:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "competitions",
            "0016_alter_custumercompetitionresult_unique_together_and_more",
        ),
        ("custumer", "0025_alter_custumersubscriptonpayment_is_blok_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="custumercompetitionresult",
            name="customer_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="results",
                to="custumer.custumer",
                verbose_name="Клиент",
            ),
        ),
    ]
