# Generated by Django 5.1.5 on 2025-11-14 17:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("competitions", "0017_alter_custumercompetitionresult_customer_id"),
        ("custumer", "0025_alter_custumersubscriptonpayment_is_blok_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="custumercompetitionresult",
            old_name="customer_id",
            new_name="customer",
        ),
        migrations.AlterUniqueTogether(
            name="custumercompetitionresult",
            unique_together={
                (
                    "competition",
                    "customer",
                    "distance",
                    "style",
                    "discipline",
                    "result_time_ms",
                )
            },
        ),
    ]
