# Generated by Django 5.1.5 on 2025-11-21 13:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "competitions",
            "0018_rename_customer_id_custumercompetitionresult_customer_and_more",
        ),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="competitions",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="competitions",
            name="end_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Дата окончания"
            ),
        ),
        migrations.AlterField(
            model_name="competitions",
            name="date",
            field=models.DateField(verbose_name="Дата начала"),
        ),
        migrations.AlterUniqueTogether(
            name="competitions",
            unique_together={("name", "location", "date", "end_date")},
        ),
    ]
