# Generated by Django 5.1.5 on 2025-12-16 07:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("competitions", "0019_alter_competitions_unique_together_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="custumercompetitionresult",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="custumercompetitionresult",
            name="result_time_ms",
            field=models.BigIntegerField(
                blank=True,
                help_text="Не заполняется при дисквалификации. Формат: мм:сс:ммм",
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Показанное время в миллисекундах",
            ),
        ),
    ]
